# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

defaults: &defaults
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>
  amount_limit: <%= ENV["AMOUNT_LIMIT"] %>
  merchant_login: <%= ENV["MERCHANT_LOGIN"] %>
  merchant_key: <%= ENV["MERCHANT_KEY"] %>
  merchant_password1: <%= ENV["MERCHANT_PASSWORD1"] %>
  merchant_password2: <%= ENV["MERCHANT_PASSWORD2"] %>
  payment_is_test: <%= ENV["PAYMENT_IS_TEST"] %>
  shop_id: <%= ENV["SHOP_ID"] %>
  scid: <%= ENV["SCID"] %>
  tax: <%= ENV["TAX"] %>

development:
  <<: *defaults
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: e5f5056665d8d0bad1a25fab28564a1edd29822af26d3d6a2adb1c424a3bec39b3904596cc014d973b052b8dd4ccb6c95c84c721c11b7fcf22a9e6ebf96ee4e6
  payment_result_url: http://localhost/dashboard/payments/success/

test:
  domain_name: example.com
  amount_limit: 20000
  tax: 10
  secret_key_base: 85153985f188d751706c2b07da3e610f7be66a69e967557cd5acaacb3b0164f1deacb035ecd431f231a89b1cd3498e923ad5bb6b4713f8c8ed66865e8c539b43

production: &production
  <<: *defaults
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  mailgun:
    username: <%= ENV["MAILGUN_USERNAME"] %>
    password: <%= ENV["MAILGUN_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  payment_result_url: <%= ENV["PAYMENT_RESULT_URL"] %>
  bugsnag_api_key: '<%= ENV["BUGSNAG_API_KEY"] %>'

staging:
  <<: *production
