#= require jquery
#= require jquery_ujs
#= require dataTables/jquery.dataTables
#= require dataTables/bootstrap/3/jquery.dataTables.bootstrap
#= require jquery-ui
#= require underscore
#= require gmaps/google
#= require kendo.all.min
#= require kendo.timezones.min
#= require cultures/kendo.culture.ru-RU.min
#= require messages/kendo.messages.ru-RU.min
#= require backbone
#= require backbone_rails_sync
#= require backbone_datalink
#= require backbone/tennis_app
#= require bootstrap-sprockets
#= require chosen.jquery
#= require gritter
#= require moment
#= require moment/ru
#= require cocoon
#= require jquery.datetimepicker
#= require dropzone
#= require lightbox
#= require ./coaches
#= require ./dashboard
#= require ./devise
#= require ./stadiums
#= require_self

kendo.culture 'ru-RU'
